apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-assetrepo
spec:
  encryptedData:
    .dockerconfigjson: AgBUjwowK1SXjcxFRJNFD5DdPY2clr3Q11CvXLEC3mMXOYhHmYj5iYmL67rdWKr/78200vNPWJO6RcknU1KfLvLIUIczF7CVs4GlSxWVZ24Ic37vUBJZqQqDtn0ip1V/IiV/HS4OSIWcJiW+4JWwfveCGDOj4Sa06KJwUqzEX7qONVlhXa6cOLucLWZ1bB5AFVzsyT9xv1PpROjJbeynPw1QykKD4JhAQW8zqsEdVKzyEhsiZEO20c0pHvvvvakQr7AhoShzchvTVNB/lOaWvTDtZMdWJjXuSdiLbGsz9sfc5fqDfXl/7AhQLxd5R4TRKYa54ekGVojweTV/X7Xni7zrv6Ni9AvWoqhm7wONneGz413/maPg/1Uegnl7yvC6FyPC4prBqBiUkVq/iJ3PD4+reoS0S87Q4k37ihdYVc0Dpk4RWsjbyRR8WnoCDB69Cgf+Ui/EqwkQzDQGMCU0oBiNTPHcXXVLa0sZ89pyQI2IRNCxOveo1YdbBqg3YfGvqE+NA2UKh0w1jYyEwE87WbnaTwF1BUfF7G4W3yku7xWvW/mcoZDbXD6oD9fR4KXOl0Ralpoh3KB1X+izbIc2Jhw4JSlX1oF8kbQFFZP9YjJV8joHWrDgzlQQijFgAZSzQluch43xFDNM6bIrGGONEXW+0L0nki4AGpvPvICoU5WS3K/CQfeOsyUBDa9ojtbiiIDpE23vZ3INxcNyhuyjqNbI6u1GfdjXnUOgP3lYOM9tQ3n1kKgduKqAB0kBFa/kzw1ftgcDHlqZscxzIK7C5I/9KpsmO4uZ9RZFys0kPwM7zx4e07R3UC/xVY758GkB9eVQ2FcK3SZZ6/pMu8GmF0+qA8+sPIswHAEnrMZkV222hrC1O/OgGhQmRJ5jciP9e9pR5eCUNVVXvJvyLjOK21c9NROdloLpzasFxFuV1LKGyItibYrGpE3McnSw4N7vYDnj5lTfoGdFn5NKGMfJmxfJL3gG5svldu7ogTDoe/zcb2bvflJtUF5p+6TiWpTKx+HaK7J5WNxg7HzzBitYNrdP+vuaW9DhaxZNjh+mrL80f0wZAoZrI4RbeIGxGODtOk6ytnWlP3XyQo1hbfhEVcYZ4gGUg54gCuHUi/VZHS3D/oeBjKgxeNgEV2VZJ86g5Frpx5mrJoJYMPaE2npCJ9bcpseMN+8AE4uHTT0LD7Dlx42Pa8qBwiiLtc3rptBBCrowcohd6YCm8a7VG0HnZr43w63r0kjqDF42TpCJ7fHB+yujsTuDE4pbFBV3o0CieGdkReE/+RwJsILs+9n6AY1OjhAs76ISRJu8kbQAqk5xjDWvBgsRKwKu/xW8gWW1lVDX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-assetrepo
    type: kubernetes.io/dockerconfigjson

